import { Recipe } from './types'

export const RECIPES: Recipe[] = [
  {
    id: '1',
    name: 'Avocado Toast with Egg',
    category: 'Breakfast',
    description: 'A simple, nutritious, and delicious breakfast to start your day.',
    ingredients: [
      { name: 'Sourdough bread', quantity: '2 slices' },
      { name: 'Avocado', quantity: '1' },
      { name: 'Eggs', quantity: '2' },
      { name: 'Red pepper flakes', quantity: '1 pinch' },
      { name: 'Salt and pepper', quantity: 'to taste' },
    ],
    instructions: [
      'Toast the sourdough bread slices until golden brown.',
      'While the bread is toasting, mash the avocado in a small bowl. Season with salt and pepper.',
      'Fry or poach the eggs to your liking.',
      'Spread the mashed avocado evenly on the toast.',
      'Top each slice with an egg and a pinch of red pepper flakes.',
      'Serve immediately.',
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    nutrients: { calories: 450, protein: 20, fat: 25, carbs: 35 },
    prepTime: 5,
    cookTime: 10,
  },
  {
    id: '2',
    name: 'Mediterranean Quinoa Salad',
    category: 'Lunch',
    description:
      'A vibrant and healthy salad, perfect for a light lunch or side dish.',
    ingredients: [
      { name: 'Quinoa', quantity: '1 cup' },
      { name: 'Water', quantity: '2 cups' },
      { name: 'Cucumber', quantity: '1' },
      { name: 'Cherry tomatoes', quantity: '1 cup' },
      { name: 'Red onion', quantity: '1/2' },
      { name: 'Kalamata olives', quantity: '1/2 cup' },
      { name: 'Feta cheese', quantity: '1/2 cup' },
      { name: 'Lemon juice', quantity: '1/4 cup' },
      { name: 'Olive oil', quantity: '2 tbsp' },
      { name: 'Fresh parsley', quantity: '1/4 cup' },
    ],
    instructions: [
      'Rinse quinoa and cook in water according to package directions. Let it cool.',
      'Chop cucumber, tomatoes, and red onion. Halve the olives.',
      'In a large bowl, combine cooled quinoa, chopped vegetables, olives, and crumbled feta cheese.',
      'In a small bowl, whisk together lemon juice, olive oil, and chopped parsley. Season with salt and pepper.',
      'Pour the dressing over the salad and toss to combine.',
      'Chill for at least 30 minutes before serving.',
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    nutrients: { calories: 550, protein: 15, fat: 30, carbs: 55 },
    prepTime: 15,
    cookTime: 20,
  },
  {
    id: '3',
    name: 'Sheet Pan Lemon Herb Chicken',
    category: 'Dinner',
    description:
      'An easy and flavorful one-pan meal with minimal cleanup.',
    ingredients: [
      { name: 'Chicken breasts', quantity: '4' },
      { name: 'Broccoli florets', quantity: '2 cups' },
      { name: 'Baby potatoes', quantity: '1 lb' },
      { name: 'Lemon', quantity: '1' },
      { name: 'Garlic cloves', quantity: '4' },
      { name: 'Olive oil', quantity: '3 tbsp' },
      { name: 'Dried oregano', quantity: '1 tsp' },
      { name: 'Dried thyme', quantity: '1 tsp' },
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Cut potatoes in half and place them in a large bowl with broccoli.',
      'Mince garlic. Zest and juice the lemon.',
      'Toss vegetables with 2 tbsp olive oil, half the garlic, salt, and pepper. Spread on a large baking sheet.',
      'Roast vegetables for 15 minutes.',
      'Meanwhile, pat chicken breasts dry. Rub with remaining olive oil, herbs, lemon zest, and garlic.',
      'After 15 minutes, add the chicken to the baking sheet. Continue to roast for 20-25 minutes, or until chicken is cooked through.',
      'Squeeze lemon juice over everything before serving.',
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    nutrients: { calories: 650, protein: 50, fat: 35, carbs: 30 },
    prepTime: 10,
    cookTime: 40,
  },
    {
    id: '4',
    name: 'Spaghetti Aglio e Olio',
    category: 'Dinner',
    description:
      'A classic Italian pasta dish that is simple, elegant, and full of flavor.',
    ingredients: [
      { name: 'Spaghetti', quantity: '200g' },
      { name: 'Garlic', quantity: '4 cloves' },
      { name: 'Olive oil', quantity: '1/4 cup' },
      { name: 'Red pepper flakes', quantity: '1/2 tsp' },
      { name: 'Fresh parsley', quantity: '1/4 cup' },
      { name: 'Parmesan cheese', quantity: 'for serving' },
    ],
    instructions: [
      'Cook spaghetti according to package directions. Reserve 1 cup of pasta water before draining.',
      'While pasta cooks, thinly slice the garlic.',
      'In a large pan, heat olive oil over medium-low heat. Add garlic and red pepper flakes. Cook until garlic is lightly golden, about 2-3 minutes.',
      'Add the drained spaghetti to the pan with the garlic oil. Toss to coat.',
      'Add about 1/4 cup of reserved pasta water and the chopped parsley. Toss continuously until a light sauce forms.',
      'Serve immediately with a generous grating of Parmesan cheese.',
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    nutrients: { calories: 500, protein: 12, fat: 25, carbs: 58 },
    prepTime: 5,
    cookTime: 15,
  },
  {
    id: '5',
    name: 'Chocolate Chip Cookies',
    category: 'Dessert',
    description:
      'The ultimate chewy and gooey chocolate chip cookies. A timeless classic.',
    ingredients: [
      { name: 'All-purpose flour', quantity: '2 1/4 cups' },
      { name: 'Baking soda', quantity: '1 tsp' },
      { name: 'Salt', quantity: '1/2 tsp' },
      { name: 'Unsalted butter', quantity: '1 cup, softened' },
      { name: 'Granulated sugar', quantity: '3/4 cup' },
      { name: 'Brown sugar', quantity: '1 cup, packed' },
      { name: 'Vanilla extract', quantity: '1 tsp' },
      { name: 'Large eggs', quantity: '2' },
      { name: 'Semi-sweet chocolate chips', quantity: '2 cups' },
    ],
    instructions: [
        'Preheat oven to 375°F (190°C).',
        'In a small bowl, whisk together flour, baking soda, and salt.',
        'In a large bowl, beat butter, granulated sugar, brown sugar, and vanilla until creamy.',
        'Add eggs, one at a time, beating well after each addition.',
        'Gradually beat in the flour mixture.',
        'Stir in chocolate chips.',
        'Drop rounded tablespoons of dough onto ungreased baking sheets.',
        'Bake for 9 to 11 minutes or until golden brown.',
        'Cool on baking sheets for 2 minutes; remove to wire racks to cool completely.',
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    nutrients: { calories: 250, protein: 3, fat: 14, carbs: 30 },
    prepTime: 15,
    cookTime: 10,
  },
]
