import { Recipe } from './types'

export const RECIPES: Recipe[] = [
  {
    id: '1',
    name: 'Avocado Toast with Egg',
    category: 'Breakfast',
    description: 'A simple, nutritious, and delicious breakfast to start your day.',
    ingredients: [
      { name: 'Sourdough bread', quantity: '2 slices' },
      { name: 'Avocado', quantity: '1' },
      { name: 'Eggs', quantity: '2' },
      { name: 'Red pepper flakes', quantity: '1 pinch' },
      { name: 'Salt and pepper', quantity: 'to taste' },
    ],
    instructions: [
      'Toast the sourdough bread slices until golden brown.',
      'While the bread is toasting, mash the avocado in a small bowl. Season with salt and pepper.',
      'Fry or poach the eggs to your liking.',
      'Spread the mashed avocado evenly on the toast.',
      'Top each slice with an egg and a pinch of red pepper flakes.',
      'Serve immediately.',
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    nutrients: { calories: 450, protein: 20, fat: 25, carbs: 35 },
    prepTime: 5,
    cookTime: 10,
  },
  {
    id: '2',
    name: 'Mediterranean Quinoa Salad',
    category: 'Lunch',
    description:
      'A vibrant and healthy salad, perfect for a light lunch or side dish.',
    ingredients: [
      { name: 'Quinoa', quantity: '1 cup' },
      { name: 'Water', quantity: '2 cups' },
      { name: 'Cucumber', quantity: '1' },
      { name: 'Cherry tomatoes', quantity: '1 cup' },
      { name: 'Red onion', quantity: '1/2' },
      { name: 'Kalamata olives', quantity: '1/2 cup' },
      { name: 'Feta cheese', quantity: '1/2 cup' },
      { name: 'Lemon juice', quantity: '1/4 cup' },
      { name: 'Olive oil', quantity: '2 tbsp' },
      { name: 'Fresh parsley', quantity: '1/4 cup' },
    ],
    instructions: [
      'Rinse quinoa and cook in water according to package directions. Let it cool.',
      'Chop cucumber, tomatoes, and red onion. Halve the olives.',
      'In a large bowl, combine cooled quinoa, chopped vegetables, olives, and crumbled feta cheese.',
      'In a small bowl, whisk together lemon juice, olive oil, and chopped parsley. Season with salt and pepper.',
      'Pour the dressing over the salad and toss to combine.',
      'Chill for at least 30 minutes before serving.',
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    nutrients: { calories: 550, protein: 15, fat: 30, carbs: 55 },
    prepTime: 15,
    cookTime: 20,
  },
  {
    id: '3',
    name: 'Sheet Pan Lemon Herb Chicken',
    category: 'Dinner',
    description:
      'An easy and flavorful one-pan meal with minimal cleanup.',
    ingredients: [
      { name: 'Chicken breasts', quantity: '4' },
      { name: 'Broccoli florets', quantity: '2 cups' },
      { name: 'Baby potatoes', quantity: '1 lb' },
      { name: 'Lemon', quantity: '1' },
      { name: 'Garlic cloves', quantity: '4' },
      { name: 'Olive oil', quantity: '3 tbsp' },
      { name: 'Dried oregano', quantity: '1 tsp' },
      { name: 'Dried thyme', quantity: '1 tsp' },
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Cut potatoes in half and place them in a large bowl with broccoli.',
      'Mince garlic. Zest and juice the lemon.',
      'Toss vegetables with 2 tbsp olive oil, half the garlic, salt, and pepper. Spread on a large baking sheet.',
      'Roast vegetables for 15 minutes.',
      'Meanwhile, pat chicken breasts dry. Rub with remaining olive oil, herbs, lemon zest, and garlic.',
      'After 15 minutes, add the chicken to the baking sheet. Continue to roast for 20-25 minutes, or until chicken is cooked through.',
      'Squeeze lemon juice over everything before serving.',
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    nutrients: { calories: 650, protein: 50, fat: 35, carbs: 30 },
    prepTime: 10,
    cookTime: 40,
  },
    {
    id: '4',
    name: 'Spaghetti Aglio e Olio',
    category: 'Dinner',
    description:
      'A classic Italian pasta dish that is simple, elegant, and full of flavor.',
    ingredients: [
      { name: 'Spaghetti', quantity: '200g' },
      { name: 'Garlic', quantity: '4 cloves' },
      { name: 'Olive oil', quantity: '1/4 cup' },
      { name: 'Red pepper flakes', quantity: '1/2 tsp' },
      { name: 'Fresh parsley', quantity: '1/4 cup' },
      { name: 'Parmesan cheese', quantity: 'for serving' },
    ],
    instructions: [
      'Cook spaghetti according to package directions. Reserve 1 cup of pasta water before draining.',
      'While pasta cooks, thinly slice the garlic.',
      'In a large pan, heat olive oil over medium-low heat. Add garlic and red pepper flakes. Cook until garlic is lightly golden, about 2-3 minutes.',
      'Add the drained spaghetti to the pan with the garlic oil. Toss to coat.',
      'Add about 1/4 cup of reserved pasta water and the chopped parsley. Toss continuously until a light sauce forms.',
      'Serve immediately with a generous grating of Parmesan cheese.',
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    nutrients: { calories: 500, protein: 12, fat: 25, carbs: 58 },
    prepTime: 5,
    cookTime: 15,
  },
  {
    id: '5',
    name: 'Chocolate Chip Cookies',
    category: 'Dessert',
    description:
      'The ultimate chewy and gooey chocolate chip cookies. A timeless classic.',
    ingredients: [
      { name: 'All-purpose flour', quantity: '2 1/4 cups' },
      { name: 'Baking soda', quantity: '1 tsp' },
      { name: 'Salt', quantity: '1/2 tsp' },
      { name: 'Unsalted butter', quantity: '1 cup, softened' },
      { name: 'Granulated sugar', quantity: '3/4 cup' },
      { name: 'Brown sugar', quantity: '1 cup, packed' },
      { name: 'Vanilla extract', quantity: '1 tsp' },
      { name: 'Large eggs', quantity: '2' },
      { name: 'Semi-sweet chocolate chips', quantity: '2 cups' },
    ],
    instructions: [
        'Preheat oven to 375°F (190°C).',
        'In a small bowl, whisk together flour, baking soda, and salt.',
        'In a large bowl, beat butter, granulated sugar, brown sugar, and vanilla until creamy.',
        'Add eggs, one at a time, beating well after each addition.',
        'Gradually beat in the flour mixture.',
        'Stir in chocolate chips.',
        'Drop rounded tablespoons of dough onto ungreased baking sheets.',
        'Bake for 9 to 11 minutes or until golden brown.',
        'Cool on baking sheets for 2 minutes; remove to wire racks to cool completely.',
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    nutrients: { calories: 250, protein: 3, fat: 14, carbs: 30 },
    prepTime: 15,
    cookTime: 10,
  },
  {
    id: '6',
    name: 'Chicken Karahi',
    category: 'Dinner',
    description: 'A fragrant and spicy Pakistani chicken dish traditionally cooked in a karahi (wok).',
    ingredients: [
      { name: 'Chicken', quantity: '1 kg, cut into pieces' },
      { name: 'Tomatoes', quantity: '4 large, chopped' },
      { name: 'Ginger paste', quantity: '1 tbsp' },
      { name: 'Garlic paste', quantity: '1 tbsp' },
      { name: 'Green chilies', quantity: '4-5, slit' },
      { name: 'Yogurt', quantity: '1/2 cup, whisked' },
      { name: 'Oil or Ghee', quantity: '1/2 cup' },
      { name: 'Cumin powder', quantity: '1 tsp' },
      { name: 'Coriander powder', quantity: '1.5 tsp' },
      { name: 'Turmeric powder', quantity: '1/2 tsp' },
      { name: 'Garam masala', quantity: '1 tsp' },
      { name: 'Fresh cilantro', quantity: 'for garnish' },
      { name: 'Julienned ginger', quantity: 'for garnish' },
    ],
    instructions: [
      'Heat oil/ghee in a karahi or a large pan over high heat.',
      'Add the chicken pieces and fry until they are lightly browned on all sides.',
      'Add ginger and garlic paste, and cook for another 2 minutes until fragrant.',
      'Add the chopped tomatoes and cook until they soften and the oil starts to separate from the masala.',
      'Stir in the cumin powder, coriander powder, turmeric powder, and salt. Mix well.',
      'Reduce the heat, add the whisked yogurt and green chilies. Cook for 5-7 minutes, stirring occasionally.',
      'Cover the karahi and let it simmer on low heat for 15-20 minutes, or until the chicken is tender and cooked through.',
      'Sprinkle with garam masala, julienned ginger, and fresh cilantro.',
      'Serve hot with naan bread or chapati.',
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    nutrients: { calories: 750, protein: 60, fat: 50, carbs: 15 },
    prepTime: 20,
    cookTime: 45,
  },
  {
    id: '7',
    name: 'Chicken Biryani',
    category: 'Dinner',
    description: 'A savory chicken and rice dish that includes layers of chicken, rice, and aromatics that are steamed together.',
    ingredients: [
        { name: 'Basmati rice', quantity: '2 cups' },
        { name: 'Chicken', quantity: '1 kg' },
        { name: 'Yogurt', quantity: '1 cup' },
        { name: 'Onions', quantity: '2, sliced' },
        { name: 'Tomatoes', quantity: '2, chopped' },
        { name: 'Ginger-garlic paste', quantity: '2 tbsp' },
        { name: 'Biryani masala', quantity: '3 tbsp' },
        { name: 'Saffron', quantity: 'a pinch' },
        { name: 'Milk', quantity: '2 tbsp' },
        { name: 'Oil', quantity: '1/2 cup' },
    ],
    instructions: [
        'Soak rice for 30 minutes. Cook until 70% done and set aside.',
        'Fry onions until golden brown. Set half aside.',
        'In the same oil, add chicken, ginger-garlic paste, and cook until chicken changes color.',
        'Add tomatoes, yogurt, and biryani masala. Cook until chicken is tender.',
        'Layer the cooked rice over the chicken. Top with fried onions, saffron-milk, and mint leaves.',
        'Cover and cook on low heat (dum) for 15-20 minutes.',
        'Gently fluff the biryani and serve hot.',
    ],
    imageUrl: 'https://placehold.co/600x400.png',
    nutrients: { calories: 850, protein: 45, fat: 35, carbs: 85 },
    prepTime: 30,
    cookTime: 60,
  },
  {
      id: '8',
      name: 'Nihari',
      category: 'Dinner',
      description: 'A slow-cooked stew of beef or lamb shank, garnished with ginger, green chilies, and lemon.',
      ingredients: [
          { name: 'Beef/Mutton shanks', quantity: '1 kg' },
          { name: 'Onion', quantity: '1, large' },
          { name: 'Ginger-garlic paste', quantity: '2 tbsp' },
          { name: 'Nihari masala', quantity: '4 tbsp' },
          { name: 'Flour (atta)', quantity: '1/4 cup' },
          { name: 'Oil', quantity: '1 cup' },
          { name: 'Water', quantity: '8 cups' },
      ],
      instructions: [
          'Heat oil, fry onion until golden.',
          'Add meat and ginger-garlic paste. Sear the meat.',
          'Add nihari masala and cook for a few minutes.',
          'Pour in water, bring to a boil, then simmer on low heat for 4-6 hours until meat is very tender.',
          'Dissolve flour in 1 cup of water to make a slurry.',
          'Slowly add the slurry to the stew, stirring constantly to avoid lumps, until the gravy thickens.',
          'Simmer for another 15-20 minutes.',
          'Garnish with julienned ginger, chopped cilantro, green chilies and a squeeze of lemon.',
      ],
      imageUrl: 'https://placehold.co/600x400.png',
      nutrients: { calories: 900, protein: 70, fat: 60, carbs: 10 },
      prepTime: 20,
      cookTime: 240,
  },
  {
      id: '9',
      name: 'Haleem',
      category: 'Dinner',
      description: 'A thick porridge made of wheat, barley, meat (usually beef or chicken), lentils, and spices.',
      ingredients: [
          { name: 'Boneless meat', quantity: '500g' },
          { name: 'Mixed lentils', quantity: '1 cup' },
          { name: 'Cracked wheat/barley', quantity: '1/2 cup' },
          { name: 'Onion', quantity: '2, sliced' },
          { name: 'Ginger-garlic paste', quantity: '2 tbsp' },
          { name: 'Haleem masala', quantity: '3 tbsp' },
          { name: 'Oil', quantity: '1/2 cup' },
      ],
      instructions: [
          'Soak lentils and wheat overnight.',
          'Cook meat with spices until tender. Shred the meat.',
          'Cook the soaked lentils and wheat until they are very soft. Blend to a paste.',
          'Combine the meat and lentil paste. Cook together for 30 minutes, stirring continuously.',
          'Prepare a tarka (tempering) of fried onions and pour over the haleem.',
          'Serve with lemon wedges, chaat masala, and fresh cilantro.',
      ],
      imageUrl: 'https://placehold.co/600x400.png',
      nutrients: { calories: 600, protein: 40, fat: 25, carbs: 50 },
      prepTime: 60,
      cookTime: 180,
  },
  {
      id: '10',
      name: 'Seekh Kebab',
      category: 'Appetizer',
      description: 'Minced meat (usually lamb or chicken) skewers, seasoned with spices and grilled.',
      ingredients: [
          { name: 'Minced meat', quantity: '500g' },
          { name: 'Onion', quantity: '1, finely chopped' },
          { name: 'Green chilies', quantity: '2, chopped' },
          { name: 'Ginger-garlic paste', quantity: '1 tbsp' },
          { name: 'Coriander leaves', quantity: 'a handful' },
          { name: 'Gram flour (besan)', quantity: '2 tbsp' },
          { name: 'Spices (cumin, coriander, garam masala)', quantity: '1 tsp each' },
      ],
      instructions: [
          'Mix all ingredients with the minced meat.',
          'Knead the mixture well.',
          'Divide into portions and shape them onto skewers.',
          'Grill or pan-fry the kebabs until cooked through.',
          'Serve hot with mint chutney and naan.',
      ],
      imageUrl: 'https://placehold.co/600x400.png',
      nutrients: { calories: 350, protein: 30, fat: 25, carbs: 5 },
      prepTime: 25,
      cookTime: 15,
  },
  {
      id: '11',
      name: 'Chapli Kebab',
      category: 'Appetizer',
      description: 'A flat, round minced meat patty, popular in Peshawar. It is known for its spicy and tangy flavor.',
      ingredients: [
          { name: 'Minced meat (beef)', quantity: '500g' },
          { name: 'Onion', quantity: '1, chopped' },
          { name: 'Tomato', quantity: '1, chopped' },
          { name: 'Green chilies', quantity: '3, chopped' },
          { name: 'Coriander seeds', quantity: '1 tbsp, crushed' },
          { name: 'Pomegranate seeds', quantity: '1 tbsp, dried' },
          { name: 'Egg', quantity: '1' },
          { name: 'Cornmeal (makki ka atta)', quantity: '1/4 cup' },
      ],
      instructions: [
          'Combine all ingredients in a large bowl.',
          'Mix thoroughly to create a uniform mixture.',
          'Shape the mixture into flat, round patties.',
          'Shallow fry in a pan with oil on medium heat until both sides are dark brown and crispy.',
          'Serve hot with naan and raita.',
      ],
      imageUrl: 'https://placehold.co/600x400.png',
      nutrients: { calories: 400, protein: 28, fat: 30, carbs: 8 },
      prepTime: 20,
      cookTime: 20,
  },
  {
      id: '12',
      name: 'Saag',
      category: 'Vegetarian',
      description: 'A popular vegetarian dish made from mustard greens (sarson) and spinach, often served with makki di roti (cornbread).',
      ingredients: [
          { name: 'Mustard greens (sarson)', quantity: '1 kg' },
          { name: 'Spinach (palak)', quantity: '500g' },
          { name: 'Green chilies', quantity: '4' },
          { name: 'Ginger', quantity: '2-inch piece' },
          { name: 'Garlic', quantity: '5 cloves' },
          { name: 'Onion', quantity: '1, chopped' },
          { name: 'Cornmeal (makki ka atta)', quantity: '2 tbsp' },
          { name: 'Ghee/Butter', quantity: '1/2 cup' },
      ],
      instructions: [
          'Wash and chop the greens.',
          'Boil the greens with green chilies, ginger, and garlic until very tender.',
          'Blend the boiled greens to a coarse paste.',
          'Add cornmeal and cook until the saag thickens.',
          'In a separate pan, prepare a tempering (tarka) by frying the onion in ghee until golden brown.',
          'Pour the tarka over the saag.',
          'Serve hot with a dollop of butter and makki di roti.',
      ],
      imageUrl: 'https://placehold.co/600x400.png',
      nutrients: { calories: 300, protein: 10, fat: 20, carbs: 25 },
      prepTime: 25,
      cookTime: 60,
  },
  {
      id: '13',
      name: 'Aloo Gosht',
      category: 'Dinner',
      description: 'A comforting and hearty curry made with meat (gosht) and potatoes (aloo) in a flavorful gravy.',
      ingredients: [
          { name: 'Mutton/Beef', quantity: '500g' },
          { name: 'Potatoes', quantity: '4, peeled and halved' },
          { name: 'Onions', quantity: '2, sliced' },
          { name: 'Tomatoes', quantity: '2, chopped' },
          { name: 'Yogurt', quantity: '1/2 cup' },
          { name: 'Ginger-garlic paste', quantity: '1 tbsp' },
          { name: 'Coriander powder', quantity: '2 tsp' },
          { name: 'Turmeric powder', quantity: '1/2 tsp' },
          { name: 'Red chili powder', quantity: '1 tsp' },
      ],
      instructions: [
          'Heat oil and fry onions until golden.',
          'Add meat and ginger-garlic paste. Cook until meat is browned.',
          'Add spices, tomatoes, and yogurt. Cook until oil separates.',
          'Add potatoes and 2 cups of water. Bring to a boil.',
          'Cover and simmer until meat and potatoes are tender.',
          'Garnish with garam masala and fresh coriander.',
          'Serve with naan or rice.',
      ],
      imageUrl: 'https://placehold.co/600x400.png',
      nutrients: { calories: 600, protein: 40, fat: 35, carbs: 30 },
      prepTime: 15,
      cookTime: 90,
  },
  {
      id: '14',
      name: 'Kofta Curry',
      category: 'Dinner',
      description: 'Spiced meatballs (koftas) simmered in a rich and flavorful tomato and yogurt-based gravy.',
      ingredients: [
          { name: 'Minced meat', quantity: '500g for koftas' },
          { name: 'Onion', quantity: '1, for koftas; 2 for gravy' },
          { name: 'Ginger-garlic paste', quantity: '1 tbsp for koftas; 1 tbsp for gravy' },
          { name: 'Tomatoes', quantity: '3, pureed for gravy' },
          { name: 'Yogurt', quantity: '1/2 cup for gravy' },
          { name: 'Gram flour (besan)', quantity: '2 tbsp for koftas' },
          { name: 'Spices for gravy', quantity: 'Coriander, Cumin, Turmeric' },
      ],
      instructions: [
          'For koftas, mix minced meat with chopped onion, ginger-garlic paste, gram flour, and spices. Form into small balls.',
          'Fry the koftas until golden brown and set aside.',
          'For the gravy, fry sliced onions until golden. Add ginger-garlic paste and tomato puree. Cook well.',
          'Add spices and yogurt. Cook until the oil separates.',
          'Add 1-2 cups of water and bring to a simmer. Gently add the fried koftas.',
          'Simmer for 10-15 minutes until the gravy thickens.',
          'Garnish with cilantro and serve hot.',
      ],
      imageUrl: 'https://placehold.co/600x400.png',
      nutrients: { calories: 700, protein: 45, fat: 50, carbs: 20 },
      prepTime: 30,
      cookTime: 45,
  },
  {
      id: '15',
      name: 'Yakhni Pulao',
      category: 'Dinner',
      description: 'A fragrant rice dish cooked in a flavorful meat broth (yakhni), which makes it lighter than a biryani.',
      ingredients: [
          { name: 'Mutton/Chicken', quantity: '500g' },
          { name: 'Basmati rice', quantity: '2 cups' },
          { name: 'Onion', quantity: '1, sliced' },
          { name: 'Whole spices', quantity: 'Bay leaf, cinnamon, cloves, cardamom' },
          { name: 'Fennel seeds', quantity: '1 tsp' },
          { name: 'Coriander seeds', quantity: '1 tsp' },
          { name: 'Yogurt', quantity: '1/2 cup' },
      ],
      instructions: [
          'To make the yakhni (broth), boil the meat with whole spices, fennel, and coriander seeds until tender. Strain the broth and reserve.',
          'In a pot, fry onions until golden.',
          'Add the cooked meat and yogurt. Cook for a few minutes.',
          'Add the soaked rice and the reserved yakhni. The liquid should be about 1.5 times the volume of the rice.',
          'Cook until rice is done and all the liquid is absorbed.',
          'Fluff the pulao and serve with raita.',
      ],
      imageUrl: 'https://placehold.co/600x400.png',
      nutrients: { calories: 750, protein: 40, fat: 30, carbs: 80 },
      prepTime: 20,
      cookTime: 60,
  },
  {
      id: '16',
      name: 'Zarda',
      category: 'Dessert',
      description: 'A traditional sweet rice dish, often made on festive occasions, flavored with saffron, cardamom, and topped with nuts and candied fruits (ashrafi).',
      ingredients: [
          { name: 'Basmati rice', quantity: '1 cup' },
          { name: 'Sugar', quantity: '1 cup' },
          { name: 'Ghee', quantity: '1/4 cup' },
          { name: 'Saffron/Yellow food color', quantity: 'a pinch' },
          { name: 'Cardamom pods', quantity: '4' },
          { name: 'Nuts and raisins', quantity: '1/2 cup' },
          { name: 'Candied fruit (ashrafi/murabba)', quantity: 'for garnish' },
      ],
      instructions: [
          'Boil rice with food color until 80% cooked. Drain and set aside.',
          'In a pan, make a sugar syrup with a little water.',
          'Add ghee and cardamom to the syrup.',
          'Carefully add the boiled rice to the syrup and mix gently.',
          'Cook on low heat (dum) until rice is fully cooked and has absorbed the syrup.',
          'Garnish with nuts, raisins, and candied fruits before serving.',
      ],
      imageUrl: 'https://placehold.co/600x400.png',
      nutrients: { calories: 450, protein: 5, fat: 15, carbs: 75 },
      prepTime: 15,
      cookTime: 40,
  },
  {
      id: '17',
      name: 'Kheer',
      category: 'Dessert',
      description: 'A creamy and aromatic rice pudding, slow-cooked with milk, sugar, and flavored with cardamom and nuts.',
      ingredients: [
          { name: 'Rice', quantity: '1/4 cup, broken' },
          { name: 'Milk', quantity: '1 liter' },
          { name: 'Sugar', quantity: '3/4 cup' },
          { name: 'Cardamom pods', quantity: '4' },
          { name: 'Almonds and pistachios', quantity: 'for garnish' },
          { name: 'Kewra water (optional)', quantity: '1 tsp' },
      ],
      instructions: [
          'Wash and soak the rice for 30 minutes.',
          'In a heavy-bottomed pan, bring the milk to a boil.',
          'Add the soaked rice and cardamom pods.',
          'Simmer on low heat, stirring frequently, until the rice is cooked and the milk has thickened (about 1-1.5 hours).',
          'Add sugar and cook for another 10 minutes until it dissolves.',
          'Add kewra water if using.',
          'Pour into serving bowls, garnish with chopped nuts.',
          'Can be served warm or chilled.',
      ],
      imageUrl: 'https://placehold.co/600x400.png',
      nutrients: { calories: 350, protein: 8, fat: 10, carbs: 60 },
      prepTime: 10,
      cookTime: 90,
  }
]
